### ISSUE TITLE
[Suggestion] Multiple skins for entities, like in HEC

### ISSUE THREAD

**Issue by villager103** [HugoBDesigner/Mari0-SE-Bugfixes#14]
One thing I particularly liked about HEC was that cubes and stuff had multiple skins that you could choose via dropdown menu. I feel like this should be added for cubes and droppers, but also potentially other items as well? I can contribute the textures for them.

**Comment by HugoBDesigner** [comment]
Perhaps most items should have a "suffix" text input option, so that they grab textures related to a particular suffix. That way, we don't have to accommodate for every item in multiple ways, or have a predetermined number of textures per item, or take up space in the UI.

**Comment by HugoBDesigner** [comment]
Closing this for organization - best to keep all HEC-related features in a single issue
